version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

